apiVersion: v1
kind: Service
metadata:
  name: node-thrive-service
spec:
  selector:
    app: node-thrive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-thrive-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-thrive
  template:
    metadata:
      labels:
        app: node-thrive
    spec:
      automountServiceAccountToken: false
      containers:
        - name: node-thrive-container
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
          image: ghcr.io/thrive-roadshow/node-thrive:latest
          ports:
            - containerPort: 9000