name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to kubernetes"
        required: true
        default: "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up kubectl aws eks
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Set up kubectl
        uses: kubectl/setup-kubectl@v1
      - name: Configure kubectl
        run: |
          aws eks --region ap-southeast-1 update-kubeconfig --name thrive-roadshow
      - name: Deploy to kubernetes
        run: |
          kubectl apply -f deploy/kubernetes/app.yaml
